spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/openedugodev
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

server:
  port: 9090  # Puerto diferente para desarrollo
